Add Ukrainian translation
RetroMusicPlayer/Paisa pull request #407
Opened 2023-12-07 09:59 UTC by AlexHladin

I've added the localization file for the Ukrainian language and registered it in the app_language_changer.dart file. Things that could be translated are translated.

2023-12-30 11:30 UTC, SahSantoshh requested changes

2023-12-30 11:30 UTC, SahSantoshh commented on lib/localization/app_uk.arb
> +  },
@AlexHladin we only need key and value to be translated. Could you please update this by remove all key with `@` :)

2023-12-30 11:30 UTC, SahSantoshh commented on lib/localization/app_uk.arb
> +  },
for more info, please check other trnaslation files/

2023-12-30 11:31 UTC, SahSantoshh commented on lib/localization/app_uk.arb
> +  },
For more info, please check other translation files

2023-12-31 11:02 UTC, AlexHladin commented on lib/localization/app_uk.arb
> +  },
@SahSantoshh updated :)

2024-01-02 08:56 UTC, SahSantoshh approved these changes

2024-03-07 11:59 UTC, h4h13 commented
This for merged in #447 closing

2024-03-07 11:59 UTC, closed without merging